### ISSUE TITLE
ArithException on GHCJS

### ISSUE THREAD

**Issue by srid** [mrkkrp/pagination#6]
0.2.1 tests fail on GHCJS only:

```
uncaught exception: ArithException
arithmetic underflow
(after 3 tests)
Exception thrown while showing test case: 'arithmetic underflow'
```

<details><summary>Full test log</summary>
<code><pre>
Test suite tests: RUNNING...

mkPagination
  when page size is zero
    throws ZeroPageSize exception
      +++ OK, passed 100 tests.
  when page index in zero
    throws ZeroPageIndex exception
      +++ OK, passed 100 tests.
  when page size and page index are positive
    we get the Pagination value
      +++ OK, passed 100 tests.
Functor instance of Paginated
  works FAILED [1]
Foldable instance of Paginated
  foldr works like with lists FAILED [2]
Traversable instance of Paginated
  traverse works like with lists FAILED [3]
paginate
  when total number of items is zero
    produces an empty pagination
      +++ OK, passed 100 tests.
paginatedItems
  number of actual items is less than or equal to page size FAILED [4]
paginatedPagination
  returns original pagination correcting index if necessary FAILED [5]
paginatedPagesTotal
  returns correct number of total pages
    +++ OK, passed 100 tests.
paginatedItemsTotal
  returns the same number of items as it was specified for paginate
    +++ OK, passed 100 tests.
hasOtherPages
  correctly detects whether we the collection has other pages
    +++ OK, passed 100 tests.
hasPrevPage
  correctly detect whether paginated data has previous page
    +++ OK, passed 100 tests.
hasNextPage
  correctly detect whether paginated data has next page
    +++ OK, passed 100 tests.
pageRange
  correctly performs generation of page ranges FAILED [6]
backwardEllip
  correctly detects when there is a backward ellipsis FAILED [7]
forwardEllip
  correctly detects when there is a forward ellipsis FAILED [8]

Failures:

  tests/Main.hs:39:5:
  1) Functor instance of Paginated works
       uncaught exception: ArithException
       arithmetic underflow
       (after 3 tests)
         Exception thrown while showing test case: 'arithmetic underflow'
         Exception thrown while showing test case: 'arithmetic underflow'

  To rerun use: --match "/Functor instance of Paginated/works/"

  tests/Main.hs:45:5:
  2) Foldable instance of Paginated foldr works like with lists
       uncaught exception: ArithException
       arithmetic underflow
       (after 3 tests and 1 shrink)
         Exception thrown while showing test case: 'arithmetic underflow'
         0
         Exception thrown while showing test case: 'arithmetic underflow'

  To rerun use: --match "/Foldable instance of Paginated/foldr works like with lists/"

  tests/Main.hs:51:5:
  3) Traversable instance of Paginated traverse works like with lists
       uncaught exception: ArithException
       arithmetic underflow
       (after 3 tests)
         Exception thrown while showing test case: 'arithmetic underflow'
         Exception thrown while showing test case: 'arithmetic underflow'

  To rerun use: --match "/Traversable instance of Paginated/traverse works like with lists/"

  tests/Main.hs:75:5:
  4) paginatedItems number of actual items is less than or equal to page size
       uncaught exception: ArithException
       arithmetic underflow
       (after 3 tests)
         Exception thrown while showing test case: 'arithmetic underflow'

  To rerun use: --match "/paginatedItems/number of actual items is less than or equal to page size/"

  tests/Main.hs:80:5:
  5) paginatedPagination returns original pagination correcting index if necessary
       uncaught exception: ArithException
       arithmetic underflow
       (after 4 tests)
         Pagination 3 4
         1

  To rerun use: --match "/paginatedPagination/returns original pagination correcting index if necessary/"

  tests/Main.hs:117:5:
  6) pageRange correctly performs generation of page ranges
       uncaught exception: ArithException
       arithmetic underflow

  To rerun use: --match "/pageRange/correctly performs generation of page ranges/"

  tests/Main.hs:134:5:
  7) backwardEllip correctly detects when there is a backward ellipsis
       uncaught exception: ArithException
       arithmetic underflow
       (after 51 tests)
         Exception thrown while showing test case: 'arithmetic underflow'
         1
         Exception thrown while showing test case: 'arithmetic underflow'

  To rerun use: --match "/backwardEllip/correctly detects when there is a backward ellipsis/"

  tests/Main.hs:139:5:
  8) forwardEllip correctly detects when there is a forward ellipsis
       uncaught exception: ArithException
       arithmetic underflow
       (after 3 tests)
         Exception thrown while showing test case: 'arithmetic underflow'
         2
         Exception thrown while showing test case: 'arithmetic underflow'

  To rerun use: --match "/forwardEllip/correctly detects when there is a forward ellipsis/"

Randomized with seed 1879078690

Finished in -721554505728000000.0000 seconds
17 examples, 8 failures
Test suite tests: FAIL
</code></pre>
</details>

**Comment by srid** [comment]
I should note that this happens only in ghcjs.

**Comment by mrkkrp** [comment]
So it's only on GHCJS? I don't use GHCJS and don't test with it. If you want to investigate, you're most welcome to try.

**Comment by mrkkrp** [comment]
@srid So is this an issue with `pagination` or GHCJS? Does it make sense to keep this one open?

**Comment by srid** [comment]
> So is this an issue with pagination or GHCJS?

Yup, I'll close this.
